<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;

class UserSeeder extends Seeder
{
    public function run(): void
    {
        $users = [
            [
                'nama' => 'Developer',
                'username' => 'dev',
                'password' => bcrypt('bhamada'),
                'nidn' => null,
                'nipy' => null,
                'prodi_id' => null,
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dev',
            ],
            [
                'nama' => 'Reno Arkan Pratama, S.M',
                'username' => 'operator',
                'password' => bcrypt('bhamada'),
                'nidn' => null,
                'nipy' => null,
                'prodi_id' => null,
                'telp' => '085900451913',
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'operator',
            ],
            [
                'nama' => 'Arif Rakhman, M.A.N',
                'username' => '0611128801',
                'password' => bcrypt('bhamada'),
                'nidn' => '0611128801',
                'nipy' => '1988.11.03.13.076',
                'prodi_id' => 1,
                'telp' => '082134916054',
                'is_ketua' => true,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Ramadhan Putra Satria, S.Kep.Ns. M.Kep',
                'username' => '0626048902',
                'password' => bcrypt('bhamada'),
                'nidn' => '0626048902',
                'nipy' => null,
                'prodi_id' => '6',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Agung Tyas Subekti, S.Kep.,M.A',
                'username' => '0630128801',
                'password' => bcrypt('bhamada'),
                'nidn' => '0630128801',
                'nipy' => null,
                'prodi_id' => '4',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Fiqih Kartika Murti, M.Pd.',
                'username' => '0628049001',
                'password' => bcrypt('bhamada'),
                'nidn' => '0628049001',
                'nipy' => null,
                'prodi_id' => '3',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'apt. Osie Listina, M.Sc.',
                'username' => '0627048403',
                'password' => bcrypt('bhamada'),
                'nidn' => '0627048403',
                'nipy' => null,
                'prodi_id' => '3',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Siswati,S.SiT., M.Kes',
                'username' => '0021078101',
                'password' => bcrypt('bhamada'),
                'nidn' => '0021078101',
                'nipy' => null,
                'prodi_id' => '5',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Ery Nourika Alfiraza, S.Si, M.Sc',
                'username' => '0608029202',
                'password' => bcrypt('bhamada'),
                'nidn' => '0608029202',
                'nipy' => null,
                'prodi_id' => '3',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Yuni Fitriani, S.Si.T., MPH',
                'username' => '0624068502',
                'password' => bcrypt('bhamada'),
                'nidn' => '0624068502',
                'nipy' => null,
                'prodi_id' => '5',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Adrestia Rifki Naharani.,SSiT.,MPH',
                'username' => '0607068701',
                'password' => bcrypt('bhamada'),
                'nidn' => '0607068701',
                'nipy' => null,
                'prodi_id' => '5',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Ike Putri Setyatama, S.ST., M.Kes',
                'username' => '0618028601',
                'password' => bcrypt('bhamada'),
                'nidn' => '0618028601',
                'nipy' => null,
                'prodi_id' => '5',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Sri Hartati, M.Kom',
                'username' => '0613057403',
                'password' => bcrypt('bhamada'),
                'nidn' => '0613057403',
                'nipy' => null,
                'prodi_id' => '9',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'apt Endang Istriningsih,M.Clin.Pharm',
                'username' => '0615028301',
                'password' => bcrypt('bhamada'),
                'nidn' => '0615028301',
                'nipy' => null,
                'prodi_id' => '3',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Sri Hidayati, M.Kep., Ns., Sp. Kep. MB',
                'username' => '0504117901',
                'password' => bcrypt('bhamada'),
                'nidn' => '0504117901',
                'nipy' => null,
                'prodi_id' => '6',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Anisa Oktiawati, M.Kep',
                'username' => '0615108602',
                'password' => bcrypt('bhamada'),
                'nidn' => '0615108602',
                'nipy' => null,
                'prodi_id' => '6',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Umi Salamah, S.Pd.,MH',
                'username' => '0622126901',
                'password' => bcrypt('bhamada'),
                'nidn' => '0622126901',
                'nipy' => null,
                'prodi_id' => '2',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Moh. Miftah, .S.E., M.M',
                'username' => '0603118802',
                'password' => bcrypt('bhamada'),
                'nidn' => '0603118802',
                'nipy' => null,
                'prodi_id' => '7',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Jumrotun Nimah,S.Kep.,Ns.M.Kep',
                'username' => '0607118002',
                'password' => bcrypt('bhamada'),
                'nidn' => '0607118002',
                'nipy' => null,
                'prodi_id' => '6',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Ita Nur Itsna, MAN',
                'username' => '0613048604',
                'password' => bcrypt('bhamada'),
                'nidn' => '0613048604',
                'nipy' => null,
                'prodi_id' => '6',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Uswatun Insani, S. Kep. Ns., M. Kep',
                'username' => '0623078103',
                'password' => bcrypt('bhamada'),
                'nidn' => '0623078103',
                'nipy' => null,
                'prodi_id' => '6',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'apt. Lailiana Garna Nurhidayati, M.Pharm.Sci.',
                'username' => '0617039302',
                'password' => bcrypt('bhamada'),
                'nidn' => '0617039302',
                'nipy' => null,
                'prodi_id' => '3',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'apt.Oktariani Pramiastuti, M.Sc.',
                'username' => '0620107801',
                'password' => bcrypt('bhamada'),
                'nidn' => '0620107801',
                'nipy' => null,
                'prodi_id' => '3',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Desi Sri Rejeki, M.Si',
                'username' => '0602128603',
                'password' => bcrypt('bhamada'),
                'nidn' => '0602128603',
                'nipy' => null,
                'prodi_id' => '3',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Ani Ratnaningsih, M.Kep.',
                'username' => '0615098703',
                'password' => bcrypt('bhamada'),
                'nidn' => '0615098703',
                'nipy' => null,
                'prodi_id' => '6',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Natiqotul Fatkhiyah, M.Kes',
                'username' => '0614128001',
                'password' => bcrypt('bhamada'),
                'nidn' => '0614128001',
                'nipy' => null,
                'prodi_id' => '5',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Susi Muryani, MSN',
                'username' => '0615058406',
                'password' => bcrypt('bhamada'),
                'nidn' => '0615058406',
                'nipy' => null,
                'prodi_id' => '2',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Firman Hidayat, M.Kep.,Ns.,Sp.Kep.J',
                'username' => '0625037401',
                'password' => bcrypt('bhamada'),
                'nidn' => '0625037401',
                'nipy' => null,
                'prodi_id' => '2',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Khodijah, M.Kep.',
                'username' => '0621038003',
                'password' => bcrypt('bhamada'),
                'nidn' => '0621038003',
                'nipy' => null,
                'prodi_id' => '2',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => true,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Deni Irawan, M.Kep.',
                'username' => '0603038504',
                'password' => bcrypt('bhamada'),
                'nidn' => '0603038504',
                'nipy' => null,
                'prodi_id' => '2',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Yessy Pramita Widodo, M.Kep.',
                'username' => '0604088903',
                'password' => bcrypt('bhamada'),
                'nidn' => '0604088903',
                'nipy' => null,
                'prodi_id' => '2',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Ikawati Setyaningrum, M.Kep.',
                'username' => '0606118602',
                'password' => bcrypt('bhamada'),
                'nidn' => '0606118602',
                'nipy' => null,
                'prodi_id' => '2',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Nurhakim Yudhi W., M.Kep.',
                'username' => '0619108504',
                'password' => bcrypt('bhamada'),
                'nidn' => '0619108504',
                'nipy' => null,
                'prodi_id' => '2',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'apt.Agung Nurcahyanta, M.Farm.',
                'username' => '0606067902',
                'password' => bcrypt('bhamada'),
                'nidn' => '0606067902',
                'nipy' => null,
                'prodi_id' => '3',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'apt. Arifina Fahamsya, M.Sc',
                'username' => '0613099102',
                'password' => bcrypt('bhamada'),
                'nidn' => '0613099102',
                'nipy' => null,
                'prodi_id' => '3',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'M. Wahab Khasbulloh,S.E.,M.M',
                'username' => '0629089203',
                'password' => bcrypt('bhamada'),
                'nidn' => '0629089203',
                'nipy' => null,
                'prodi_id' => '8',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Muammar Afif Al Qusaeri,S.E.,M.M',
                'username' => '0625068601',
                'password' => bcrypt('bhamada'),
                'nidn' => '0625068601',
                'nipy' => null,
                'prodi_id' => '8',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Toto Sudibyo.,S.E.,M.M',
                'username' => '0624068101',
                'password' => bcrypt('bhamada'),
                'nidn' => '0624068101',
                'nipy' => null,
                'prodi_id' => '7',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Nurkhayati.,S.E.,M.M',
                'username' => '0628128503',
                'password' => bcrypt('bhamada'),
                'nidn' => '0628128503',
                'nipy' => null,
                'prodi_id' => '7',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Ulumudin.,M.Kom',
                'username' => '0613069104',
                'password' => bcrypt('bhamada'),
                'nidn' => '0613069104',
                'nipy' => null,
                'prodi_id' => '9',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Haries Anom Susetyo Aji N.,M.Kom',
                'username' => '0604079102',
                'password' => bcrypt('bhamada'),
                'nidn' => '0604079102',
                'nipy' => null,
                'prodi_id' => '9',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Sonhaji.,M.Kom',
                'username' => '0618126701',
                'password' => bcrypt('bhamada'),
                'nidn' => '0618126701',
                'nipy' => null,
                'prodi_id' => '9',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Arriani Indrastuti, SKM., M.Kes.',
                'username' => '0605037601',
                'password' => bcrypt('bhamada'),
                'nidn' => '0605037601',
                'nipy' => null,
                'prodi_id' => '6',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Dr. Risnanto, M.Kes.',
                'username' => '0630067203',
                'password' => bcrypt('bhamada'),
                'nidn' => '0630067203',
                'nipy' => null,
                'prodi_id' => '6',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Arifin Dwi Atmadja, M.Kep.',
                'username' => '0611077502',
                'password' => bcrypt('bhamada'),
                'nidn' => '0611077502',
                'nipy' => null,
                'prodi_id' => '6',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Evi Supriyattun, M.Kep.',
                'username' => '0617028904',
                'password' => bcrypt('bhamada'),
                'nidn' => '0617028904',
                'nipy' => null,
                'prodi_id' => '6',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Woro Hapsari, M.Kep.',
                'username' => '0613028001',
                'password' => bcrypt('bhamada'),
                'nidn' => '0613028001',
                'nipy' => null,
                'prodi_id' => '6',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Masturoh, SST., MPH.',
                'username' => '0614048702',
                'password' => bcrypt('bhamada'),
                'nidn' => '0614048702',
                'nipy' => null,
                'prodi_id' => '5',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Tri Agustina Hadiningsih, SST.,M.Kes',
                'username' => '0625087901',
                'password' => bcrypt('bhamada'),
                'nidn' => '0625087901',
                'nipy' => null,
                'prodi_id' => '5',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Sri Tanjung Rejeki, SST.,MPH',
                'username' => '0601068802',
                'password' => bcrypt('bhamada'),
                'nidn' => '0601068802',
                'nipy' => null,
                'prodi_id' => '5',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Ika Esti Anggraeni, SST.,MPH',
                'username' => '0616098704',
                'password' => bcrypt('bhamada'),
                'nidn' => '0616098704',
                'nipy' => null,
                'prodi_id' => '5',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Rina Febri Wahyuningsih, S.SiT.',
                'username' => '0601028602',
                'password' => bcrypt('bhamada'),
                'nidn' => '0601028602',
                'nipy' => null,
                'prodi_id' => '5',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Rosmalia, S.T., M.Kes.',
                'username' => '0607117602',
                'password' => bcrypt('bhamada'),
                'nidn' => '0607117602',
                'nipy' => null,
                'prodi_id' => '4',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Erna Agustin Sukmandari, S.KM., M.P.H.',
                'username' => '0913088603',
                'password' => bcrypt('bhamada'),
                'nidn' => '0913088603',
                'nipy' => null,
                'prodi_id' => '4',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Anggit Pratiwi, S.Si., MPH.',
                'username' => '0611028902',
                'password' => bcrypt('bhamada'),
                'nidn' => '0611028902',
                'nipy' => null,
                'prodi_id' => '4',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Triyono Rakhmadi, S.KM., M.KKK.',
                'username' => '0608057201',
                'password' => bcrypt('bhamada'),
                'nidn' => '0608057201',
                'nipy' => null,
                'prodi_id' => '4',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Dwi Atmoko, M.Pd.',
                'username' => '0631018704',
                'password' => bcrypt('bhamada'),
                'nidn' => '0631018704',
                'nipy' => null,
                'prodi_id' => '4',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Agus Budianto, M.Kep.',
                'username' => '0611077102',
                'password' => bcrypt('bhamada'),
                'nidn' => '0611077102',
                'nipy' => null,
                'prodi_id' => '1',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => true,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Wisnu Widiantoro, M.Kep.',
                'username' => '0624027202',
                'password' => bcrypt('bhamada'),
                'nidn' => '0624027202',
                'nipy' => null,
                'prodi_id' => '1',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Dwi Budi Prastiani, M.Kep.',
                'username' => '0619057401',
                'password' => bcrypt('bhamada'),
                'nidn' => '0619057401',
                'nipy' => null,
                'prodi_id' => '1',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Ratna Widhiastuti, M.Kep.',
                'username' => '0516028802',
                'password' => bcrypt('bhamada'),
                'nidn' => '0516028802',
                'nipy' => null,
                'prodi_id' => '1',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Rito Cipta Sigitta H, M.Kom',
                'username' => '0619128301',
                'password' => bcrypt('bhamada'),
                'nidn' => '0619128301',
                'nipy' => null,
                'prodi_id' => '9',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Prihastini Setyo Wulandari, M.Farm',
                'username' => '0603109703',
                'password' => bcrypt('bhamada'),
                'nidn' => '0603109703',
                'nipy' => null,
                'prodi_id' => '3',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
            [
                'nama' => 'Wiliyanto, S.E.,M.M',
                'username' => '0615098704',
                'password' => bcrypt('bhamada'),
                'nidn' => '0615098704',
                'nipy' => null,
                'prodi_id' => '8',
                'telp' => null,
                'is_ketua' => false,
                'is_peninjau' => false,
                'role' => 'dosen',
            ],
        ];

        User::insert($users);
    }
}
